# Copyright 2024 Michael F. Collins, III
#
# # Michael Collins's Website © 2024 by Michael F. Collins, III is licensed
# under CC BY 4.0. To view a copy of this license, visit 
# http://creativecommons.org/licenses/by/4.0/

copyright: Copyright 2024 Michael F. Collins, III
defaultContentLanguage: en
enableEmoji: true
enableRobotsTXT: true
languageCode: en-US
markup:
  asciidocExt:
    extensions:
      - asciidoctor-diagram
      - asciidoctor-html5s
menus:
  main:
    - name: Home
      pageRef: /
      weight: 10
    - name: About
      pageRef: /about
      weight: 20
    - name: Blog
      pageRef: /blog
      weight: 30
    # - name: Projects
    #   pageRef: /projects
    #   weight: 40
    # - name: Recipes
    #   pageRef: /recipes
    #   weight: 50
    - name: LinkedIn
      post: <i class="bx bxl-linkedin"></i>
      url: https://www.linkedin.com/in/michaelfcollins3/
      weight: 60
      params:
        isSocial: true
    - name: GitHub
      post: <i class="bx bxl-github"></i>
      url: https://www.github.com/mfcollins3
      weight: 70
      params:
        isSocial: true
newContentEditor: code
permalinks:
  page:
    blog: /blog/:year/:month/:slug/
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^(dart-)?sass(-embedded)?$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^asciidoctor$
    osEnv:
      - (?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GEM_PATH|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
  http:
    mediaTypes: null
    methods:
      - (?i)GET|POST
    urls:
      - .*
theme: normal
timeZone: America/Phoenix
title: Michael F. Collins, III
