# Copyright 2024 Michael F. Collins, III
#
# # Michael Collins's Website © 2024 by Michael F. Collins, III is licensed
# under CC BY 4.0. To view a copy of this license, visit 
# http://creativecommons.org/licenses/by/4.0/

baseURL: http://localhost:4280
buildDrafts: true
buildExpired: false
buildFuture: true
cleanDestinationDir: true
enableMissingTranslationPlaceholders: true
