# Copyright 2024 Michael F. Collins, III
#
# Michael Collins's Website © 2024 by Michael F. Collins, III is licensed
# under CC BY 4.0. To view a copy of this license, visit 
# http://creativecommons.org/licenses/by/4.0/

name: Publish Website

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  HUGO_VERSION: 0.124.0
  RUBY_VERSION: 3.1.4
  
jobs:
  build_and_deploy_job:
    name: Build and Deploy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Node.js tools
        run: npm ci
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION}}
          bundler-cache: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION}}
          extended: true
      - name: Build the website
        run: |
          export PATH=$GEM_PATH/bin:$PATH
          npx swa build
        env:
          GEM_PATH: ${{ github.workspace }}/vendor/bundle/ruby/3.1.0
      - name: Publish the preview website
        if: ${{ github.event_name == 'pull_request' }}
        run: npx swa deploy --env preview
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      - name: Publish the production website
        if: ${{ github.event_name == 'push' }}
        run: npx swa deploy --env production
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
